config/routes.rb
Packet::Application.routes.draw do
  resources :signatures, only: [:index, :create, :destroy]
  resources :upperclassmen, only: [:index, :show, :update]
  resources :freshmen, only: [:create, :destroy, :index, :show, :update, :edit]
  resources :stats, only: [:index]
  resource  :sessions, only: [:new, :create, :destroy]
  root to: "upperclassmen#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Tal Cohen">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <title><%= @title %></title>

    <!-- Custom styles for this template -->
    <style>

      body {
        padding-top: 70px;
        padding-bottom: 30px;
      }

      .theme-dropdown .dropdown-menu {
        position: static;
        display: block;
        margin-bottom: 20px;
      }

      .theme-showcase > p > .btn {
        margin: 5px 0;
      }

    </style>
</head>

<body role="document">


    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if @current_freshman %>
            <%= link_to 'Packet', signatures_path, { class: "navbar-brand" } %>
          <% else %>
            <%= link_to root_path, { class: "navbar-brand" } do %>
              <span class="talpacket hidden">Tal </span>Packet
            <% end %>
          <% end %>
        </div>
        <% if @current_freshman or @current_upperclassman %>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <% if @current_upperclassman %>
                <li <% if current_page?(upperclassman_path(@current_upperclassman.id)) or current_page?(root_path) %>class="active"<% end %>>
                  <%= link_to upperclassman_path(@current_upperclassman.id) do %>
                    My <span class="talpacket hidden">Tal Packet </span>Signatures
                  <% end %>
              <% elsif @current_freshman %>
                <li <% if current_page?(freshman_path(@current_freshman.id)) %>class="active"<% end %>>
                  <% if @current_freshman.doing_packet and @current_freshman.on_packet %>
                    <%= link_to 'My Packet / Signatures', freshman_path(@current_freshman.id) %>
                  <% elsif @current_freshman.on_packet %>
                    <%= link_to 'My Signatures', freshman_path(@current_freshman.id) %>
                  <% else %>
                    <%= link_to 'My Packet', freshman_path(@current_freshman.id) %>
                  <% end %>
                </li>
              <% end %>
              <li <% if current_page?(freshmen_path) %>class="active"<% end %>>
                <%= link_to freshmen_path do %>
                  <span class="default-theme hidden">Freshmen Packets</span><span class="talpacket hidden">Tal Packets</span>
                <% end %>
              </li>
              <% unless @current_freshman %>
                <li <% if current_page?(upperclassmen_path) %>class="active"<% end %>>
                  <%= link_to upperclassmen_path do %>
                    Upperclassmen <span class="default-theme hidden">Signatures</span><span class="talpacket hidden">Tal Packets</span>
                  <% end %>
                </li>
                <li <% if current_page?(signatures_path) %>class="active"<% end %>>
                  <%= link_to  signatures_path do %>
                    Grid<span class="talpacket hidden"> Tal Packet</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
            <% if @current_freshman %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Logout', "/sessions", method: :delete %></li>
              </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <div class="navbar-btn">
                    <button type="button" id="toggle-talpacket" class="btn btn-default" data-upper=<%= @current_upperclassman.id %> data-active=<%= @current_upperclassman.talpacket_theme %>>It's all about Tal!</button>
                  </div>
                </li>
              </ul>
            <% end %>
            <form class="nav navbar-form navbar-right">
              <input type="text" id="user-search" class="form-control" autocomplete="off" data-provide="typeahead" placeholder="Search">
            </form>
          </div><!--/.nav-collapse -->
        <% end %>
      </div>
    </div>

    <div class="container theme-showcase" role="main">

    <% if flash[:success] %>
      <div class="alert alert-success"><%= flash[:success] %></div>
    <% end %>

    <% if flash[:error] %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>
 
    <%= yield %>

    <div class="row">
      <footer class="text-center" style="font-weight:bold;font-size:1.2em;">Tal - <a href="https://github.com/TalCohen/CSHWebPacket">Packet</a></footer>
    </div>

    <div class="hidden">
      <ul>
        <% @all_upperclassmen.each do |u| %>
          <li class="search-upperclassman" data-id="<%= u.id %>" data-name="<%= u.name %>"></li>
        <% end %>
      </ul>
      <ul>
        <% @all_freshmen.each do |f| %>
          <li class="search-freshman" data-id="<%= f.id %>" data-name="<%= f.name %>"></li>
        <% end %>
      </ul>
    </div>

    </div> <!-- /container -->
</body>
</html>